#!/usr/bin/env node
'use strict';
const assert = require('assert');
const child_process = require('child_process');
const fs = require('fs-extra');
const path = require('path');
const rp = require('request-promise-native');

let log = () => {};
const statistics = {
  LinesChanged: 0,
  LinesAdded: 0,
  LinesRemoved: 0,
};
let async_tasks = [];
let options;

function parseArgs(args) {
  const minimist = require('minimist');
  args = args || process.argv.slice(2);
  const options = minimist(args, {
    boolean: ['deflake', 'no-commit', 'remove', 'sort', 'verbose'],
    string: ['bug', 'expects', 'file', 'path', 'rebaseline'],
    alias: {
      b: 'bug',
      d: 'deflake',
      e: 'expects',
      f: 'file',
      n: 'no-commit',
      p: 'path',
      r: 'rebaseline',
      s: 'sort',
      v: 'verbose',
    },
    default: {
      expects: '*',
    },
    unknown: arg => {
      if (arg.startsWith('-')) {
        throw new Error(`Unknown option ${arg}
Usage: ${path.basename(__filename)} [options] [results.json...]
  -b <bug>: The bug number/string for new entries.
  -d: De-flake if all results are pass.
  -e <expect,expect,...>: Update specified expects only.
     If the expect starts with '-', it is ignored instead.
  -f <file>: The TestExpectations file path.
  -p <string>: Only include tests with the specified path.
     If the path starts with '-', it is excluded instead.
  -r <test paths>: Rebaseline specified tests instead of adding to expectations.
     Test paths is space or newline delimited string.
     When it's '-', it's read from stdin.
     When it's 'spaces', space-only failures will be rebaselined.
  --remove: Remove entries where test files are missing in the local file system.
  -s: Sort the output.
  -v: Verbose.
`);
      }
      return true;
    },
  });
  if (options.verbose)
    log = console.log.bind(console);
  log.files = [];
  log.warnings = [];
  log.warn = msg => {
    log(msg);
    log.warnings.push(msg);
  };
  if (options.bug && options.bug.match(/^\d/))
    options.bug = 'crbug.com/' + options.bug;
  options.expects = (args => {
    if (!args.length)
      return {};
    if (args[0][0] === '-')
      args = ['*'].concat(args);
    let expects = {};
    for (let arg of args) {
      if (arg === '*') {
        for (let e of ['Pass', 'Failure', 'Crash', 'Timeout'])
          expects[e] = 0;
      } else if (arg[0] === '-') {
        delete expects[arg.slice(1)];
      } else {
        expects[arg] = 0;
      }
    }
    return expects;
  })(argAsArray(options.expects));
  options.shouldUpdate = (args => {
    if (!args.length)
      return () => true;
    return testPath => {
      let whenNotFound = true;
      for (let arg of args) {
        if (arg.startsWith('-')) {
          if (testPath.includes(arg.slice(1)))
            return false;
        } else {
          if (testPath.includes(arg))
            return true;
          whenNotFound = false;
        }
      }
      return whenNotFound;
    };
  })(argAsArray(options.path));
  options.shouldRebaseline = (args => {
    if (!args.length)
      return null;
    if (args.length === 1 && args[0] === 'spaces') {
      return result => {
        if (result.actual.is('TEXT')) {
	  switch (result.textMismatchCategory) {
	    case 'spaces and tabs only':
	    case 'newlines only':
	    case 'spaces, tabs and newlines only':
              return true;
	  }
	}
	return false;
      };
    }
    let byPath = arrayToDict(args);
    return result => result.path in byPath;
  })(argAsArray(options.rebaseline));
  options.testResultsUrl = build => {
    return `https://test-results.appspot.com/data/layout_results/linux_layout_tests_layout_ng/${build}/layout-test-results/full_results.json`;
  };
  return options;
}

function argAsArray(arg) {
  if (!arg)
    return [];
  if (arg === '-')
    arg = fs.readFileSync('/dev/stdin').toString();
  if (!Array.isArray(arg))
    arg = arg.split(/[, \n]/).filter(p => p);
  return arg;
}

function arrayToDict(array, value = true) {
  let dict = {};
  for (let i of array)
    dict[i] = value;
  return dict;
}

function sleep(ms){
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function downloadUrl(url, dest) {
  log(`Downloading from ${url}`);
  let body;
  for (let retry = 0; ; ) {
    try {
      body = await rp(url);
      break;
    } catch (error) {
      if (++retry > 3)
        throw error;
      if (error.statusCode && error.statusCode < 500)
        throw error;
      log.warn(`${error}\nRetrying ${retry} from ${url}`);
      await sleep(1000);
    }
  }
  await fs.outputFile(dest, body);
  log(`Download completed from ${url}`);
}

class TestResultTypes {
  constructor(types = []) {
    if (Array.isArray(types))
      this.types = types;
    else
      this.types = types.trim().split(/\s+/).filter(t => t);
  }

  get length() { return this.types.length; }

  get shouldNotUpdate() {
    return this.types.length == 1 &&
        (this.types[0] == 'Skip' ||
         this.types[0] == 'NeedsRebaseline' ||
         this.types[0] == 'NeedsManualRebaseline');
  }

  is(type) {
    return this.types.length == 1 && this.types[0] == type;
  }

  get isPassOnly() {
    return this.is('Pass');
  }

  toArray() {
    return this.types;
  }

  deflake(actualExpectations) {
    if (!actualExpectations.length)
      return;
    // Don't remove '[ Pass ]', it's to override expectations in different expectations file.
    if (this.isPassOnly)
      return;

    let actualExpectationDict = arrayToDict(actualExpectations);
    if (Object.keys(actualExpectationDict).length == 1 &&
	actualExpectations[0] == 'Pass') {
      this.types = [];
      return;
    }

    this.types = this.types
	.filter(e => e in actualExpectationDict);
  }
}

class TestExpectation {
  constructor(bug, testPath, expectations = new TestResultTypes(), conditions, trailing) {
    this.bug = bug;
    this.path = testPath;
    if (!(expectations instanceof TestResultTypes))
      expectations = new TestResultTypes(expectations);
    this.expectations = expectations;
    this.conditions = conditions;
    this.trailing = trailing;
    this.isRemoved = false;
    this.actualExpectations = [];
    this.shouldNotUpdate = this.expectations.shouldNotUpdate;
  }

  static parse(line) {
    if (line.expectations)
      return line;
    let match = line.match(/^(\S*)\s+(\[([^\]]+)]\s+)?(\S+)\s+\[([^\]]+)](.*)/);
    if (match) {
      return new TestExpectation(match[1], match[4], new TestResultTypes(match[5]), match[3], match[6]);
    }
    return null;
  }

  static isTestExpectation(obj) {
    return obj instanceof TestExpectation;
  }

  get filePath() {
    return this.path.replace(/^virtual\/[^/]*\//, '');
  }

  get shouldUpdate() {
    return !this.shouldNotUpdate && options.shouldUpdate(this.path);
  }

  toString() {
    if (this.isRemoved)
      return null;
    let output = [ this.bug ? this.bug : '' ];
    if (this.conditions)
    output = output.concat('[', this.conditions.trim(), ']');
    output = output.concat(this.path, '[', this.expectations.toArray(), ']');
    return output.join(' ') + (this.trailing ? this.trailing : '');
  }

  remove() {
    assert(!this.isRemoved);
    this.isRemoved = true;
    statistics.LinesRemoved++;
  }

  addActualExpectations(actualExpectations) {
    Array.prototype.push.apply(this.actualExpectations,
			       actualExpectations);
  }

  update(result) {
    //log(`${this.path}: ${result.actual}`);
    if (this.shouldNotUpdate)
      return 0;
    let addCount = 0;
    for (let expect of result.actualExpectations) {
      if (!(expect in statistics) || this.expectations.types.includes(expect))
        continue;
      log(`  Adding ${expect} to ${this.path}`);
      this.expectations.types.push(expect);
      statistics[expect]++;
      addCount++;
    }
    if (addCount) {
      this.expectations.types.sort();
      statistics.LinesChanged++;
    }
    return addCount;
  }

  deflake() {
    let before = this.expectations.types;
    this.expectations.deflake(this.actualExpectations);
    let deflaked = this.expectations.types;
    if (before.length === deflaked.length)
      return;
    if (!deflaked.length) {
      log(`  Removing all passes: ${this.path}`);
      this.remove();
      return;
    }
    log(`  Deflaking from ${before} to ${deflaked}: ${this.path}`);
    statistics.LinesDeflaked = statistics.LinesDeflaked || 0;
    statistics.LinesDeflaked++;
  }

  exists(testRoot) {
    return fs.existsSync(path.resolve(testRoot, this.filePath));
  }
}

class TestExpectations {
  constructor(file) {
    this.path = file;
    log(`Reading expectations file from ${file}`);
    let inputText = fs.readFileSync(file, 'utf8');
    this.parse(inputText);
  }

  parse(inputText) {
    let lines = inputText.trimRight().split(/\r?\n/)
    let tests = [];
    this.testByPath = {};
    for (let line of lines) {
      let test = TestExpectation.parse(line);
      if (!test) {
        tests.push(line);
      } else {
        tests.push(test);
        this.testByPath[test.path] = test;
      }
    }
    this.lines = tests;
  }

  write() {
    let lines = this.lines
      .filter(test =>
        !TestExpectation.isTestExpectation(test) ||
        !test.isRemoved);
    fs.writeFileSync(this.path, lines.join('\n') + '\n', 'utf8');
  }

  get expectations() {
    return this.lines.filter(test =>
      TestExpectation.isTestExpectation(test) && !test.isRemoved);
  }

  expectation(testPath) {
    assert(testPath);
    return this.testByPath[testPath];
  }

  add(expectation) {
    assert(TestExpectation.isTestExpectation(expectation) && !expectation.isRemoved);
    this.lines.push(expectation);
    this.testByPath[expectation.path] = expectation;
    statistics.LinesAdded++;
  }

  addActualExpectations(results) {
    for (let result of results) {
      if (!result.shouldUpdate)
        continue;
      // if (!is_unexpected) continue;
      let expectation = this.expectation(result.path);
      if (!expectation)
        continue;
      expectation.addActualExpectations(result.actualExpectations);
    }
  }

  update(results) {
    log(`Updating expectations from ${results.toString()}`);
    for (let result of results) {
      if (!result.shouldUpdate || !result.isUnexpected)
        continue;
      let expectation = this.expectation(result.path);
      let isNew = !expectation;
      if (isNew)
        expectation = new TestExpectation(options.bug, result.path);
      expectation.update(result);
      if (isNew && expectation.expectations.length)
        this.add(expectation);
    }
  }

  deflake() {
    log(`De-flaking...`);
    for (let expectation of this.expectations) {
      if (expectation.shouldUpdate)
        expectation.deflake();
    }
  }

  removeIfNotExists(testRootDir) {
    if (!testRootDir)
      testRootDir = TestExpectations.findTestRootDir(this.path);
    log(`Checking non-existent tests in ${testRootDir}`);
    return this.removeIf(test => {
      if (test.path && !test.exists(testRootDir)) {
        log(`  Removing non-existent test: ${test.path}`);
        statistics.LinesRemoved++;
        return true;
      }
      return false;
    });
  }

  sort() {
    let input = this.lines;
    let output = [];
    let comparer = (a, b) => {
      assert.notEqual(a.path, b.path);
      return a.path < b.path ? -1 : 1;
    };
    while (input.length) {
      let i = 0;
      for (; i < input.length; i++)
        if (TestExpectation.isTestExpectation(input[i]))
          break;
      if (i) {
        output = output.concat(input.slice(0, i));
        input = input.slice(i);
      }
      i = 0;
      for (; i < input.length; i++)
        if (!TestExpectation.isTestExpectation(input[i]))
          break;
      if (i) {
        let tests = input.slice(0, i);
        tests.sort(comparer);
        output = output.concat(tests);
        input = input.slice(i);
      }
    }
    this.lines = output;
  }

  static webKitDir(hintDir) {
    let dir = process.env['WEBKIT'];
    if (dir)
      return dir;
    dir = process.env['CHROMIUM_SRC'];
    if (dir)
      return path.join(dir, 'third_party', 'WebKit');
    for (dir = path.resolve(hintDir || '.');;) {
      let d = path.join(dir, 'WebKit');
      if (fs.existsSync(d))
        return d;
      let parent = path.dirname(dir);
      if (parent === dir)
        break;
      dir = parent;
    }
    throw new Error('WebKit directory not found (set WEBKIT or CHROMIUM_SRC)');
  }

  static findTestRootDir(hintDir) {
    return path.join(TestExpectations.webKitDir(hintDir), 'LayoutTests');
  }
}

class TestResult {
  constructor(testPath, result) {
    this.path = testPath;
    this.result = result;
  }

  get isUnexpected() {
    return this.result.is_unexpected;
  }

  get isRefTest() {
    let type = this.result['reftest_type'];
    return type && type[0] === '==';
  }

  get shouldRebaseline() {
    return options.shouldRebaseline(this);
  }

  get shouldUpdate() {
    return options.shouldUpdate(this.path);
  }

  get actual() {
    return new TestResultTypes(this.result.actual);
  }

  get actualExpectations() {
    return this.result.actual.split(/ +/).map(actual => {
      switch (actual) {
        case 'PASS':
          return 'Pass';
        case 'IMAGE':
        case 'TEXT':
        case 'IMAGE+TEXT':
          return 'Failure';
        case 'CRASH':
          return 'Crash';
        case 'TIMEOUT':
          return 'Timeout';
        case 'MISSING':
          return 'Skip';
        case 'SKIP':
          return null;
        default:
          throw new Error(`Unknown actual ${actual}`);
      }
    }).filter(expect => expect != null);
  }

  get textMismatchCategory() {
    return this.result.text_mismatch;
  }

  * rebaselineDataFromActual(actual) {
    let name = this.path.replace(/\.[a-z]+$/, '');
    for (let type of actual.split('+')) {
      let ext = null;
      switch (type) {
        case 'IMAGE':
          ext = '.png';
          break;
        case 'TEXT':
          ext = '.txt';
          break;
        default:
          throw new Error(`Cannot rebaseline for '${actual}: ${this.path}`);
      }
      yield {
	source: name + '-actual' + ext,
	dest: name + '-expected' + ext,
      };
    }
  }

  rebaseline(results, expectations) {
    if (!this.shouldRebaseline)
      return false;
    if (this.isRefTest) {
      log.warn(`Cannot rebaseline a ref-test: ${this.path}`);
      return false;
    }
    let actuals = this.result.actual.split(/ +/);
    if (actuals.length !== 1) {
      log.warn(`  Ignore rebaseline due to flaky: ${this.path}`);
      return false;
    }
    let testPath = path.parse(this.path);
    let refPath = path.join(results.testRootDir, testPath.dir, testPath.name + '-expected' + testPath.ext);
    if (fs.existsSync(refPath)) {
      log.warn(`  Ignore rebaseline of ref test: ${this.path}`);
      return false;
    }
    log(`  Rebaseline ${actuals[0]} for ${this.path}`);
    let downloads = [];
    for (let download of this.rebaselineDataFromActual(actuals[0])) {
      let source = results.sourceDir + download.source;
      let dest = path.join(results.rebaselineDir, download.dest);
      downloads.push(downloadUrl(source, dest)
		     .then(() => log.files.push(dest)));
    }
    let task = Promise.all(downloads)
	.then(() => {
	  let expectation = expectations.expectation(this.path);
	  if (expectation)
	    expectation.remove();
	  else
            log.warn(`Expectation for ${this.path} not found in ${expectations.path}`);
	});
    async_tasks.push(task);
    return true;
  }
}

class TestResults {
  constructor(results, sourcePath) {
    this.data = results;
    if (sourcePath) {
      this.sourcePath = sourcePath;
      this.sourceDir = path.dirname(sourcePath) + '/';
    }
  }

  static async load(file = TestResults.defaultPath) {
    // If this is a build#, download from the layout-test-archive.
    let sourcePath = file;
    if (/^[0-9]+$/.test(file) && !fs.existsSync(file)) {
      let build = file;
      sourcePath = options.testResultsUrl(build);
      file = path.join(process.env.HOME, 'ng-bot', build + '.json');
      if (!fs.existsSync(file)) {
        await downloadUrl(sourcePath, file);
      }
    }

    log(`Loading results from ${file}`);
    let content = fs.readFileSync(file, 'utf8');
    // Convert "ADD_RESULTS({...});" to a normal JSON.
    content = content.replace(/^[A-Z_]*\(/, '');
    content = content.replace(/\);$/, '');
    return new TestResults(JSON.parse(content), sourcePath);
  }

  static loadArgs(args) {
    let list = [];
    for (let arg of args) {
      if (!fs.existsSync(arg) && 'try-results'.startsWith(arg)) {
	TestResults.loadTryResults(list);
	continue;
      }
      list.push(TestResults.load(arg));
    }
    return list;
  }

  static loadTryResults(list = []) {
    log('Running "git cl try-results"...');
    let results = child_process.execFileSync(
	'git', ['cl', 'try-results', '--json=-']);
    for (let build of TestResults.parseTryResults(results)) {
      list.push(TestResults.load(build));
    }
    return list;
  }

  static parseTryResults(results, list = []) {
    results = JSON.parse(results);
    for (let result of results) {
      let build = result.url.match(/\/(\d+)$/);
      build = build ? build[1] : null;
      log(`Build #${build} ${result.result} ${result.status}`);
      if (result.status !== 'COMPLETED')
        continue;
      list.push(build);
    }
    return list;
  }

  get message() {
    if (this.data.build_number)
      return this.data.build_number;
    return this.sourcePath;
  }

  get regressionCount() {
    return this.data.num_regressions;
  }

  findExpectedFile(expectedPath, platforms) {
    let testRootDir = this.testRootDir;
    if (platforms) {
      let platformDir = path.join(testRootDir, 'platform');
      for (let platform of platforms) {
        let p = path.join(platformDir, platform, expectedPath);
        if (fs.existsSync(p))
          return p;
      }
    }
    expectedPath = path.join(testRootDir, expectedPath);
    if (fs.existsSync(expectedPath))
      return expectedPath;
    return null;
  }


  get testRootDir() {
    if (this._testRootDir)
      return this._testRootDir;

    // Try the directory in results JSON.
    // It may not exist if the JSON is produced in other machines.
    this._testRootDir = this.data.layout_tests_dir;
    if (this._testRootDir && fs.existsSync(this._testRootDir)) {
      log(`Test root directory: ${this._testRootDir}`);
      return this._testRootDir;
    }

    this._testRootDir = TestExpectations.findTestRootDir();
    if (this._testRootDir && fs.existsSync(this._testRootDir)) {
      log(`Test root directory: ${this._testRootDir}`);
      return this._testRootDir;
    }

    throw new Error('Test root directory not found');
  }

  get rebaselineDir() {
    let dir = this.testRootDir;
    dir = path.join(dir, 'flag-specific', 'enable-blink-features=LayoutNG');
    return dir;
  }

  toString() {
    if (this.data.builder_name)
      return `${this.data.build_number}@${this.data.builder_name}`;
    return `local (${this.sourcePath})`;
  }

  [Symbol.iterator]() {
    return this.resultsRecursive(this.data.tests, '');
  }

  * resultsRecursive(result, testPath) {
    if (result.actual) {
      yield new TestResult(testPath, result);
      return;
    }

    for (let name in result) {
      yield* this.resultsRecursive(result[name], testPath ? testPath + '/' + name : name);
    }
  }

  result(testPath) {
    let result = this.data.tests;
    for (let name of testPath.split(/\//)) {
      result = result[name];
      if (!result)
        return null;
    }
    if (!result.actual) {
      // Skip entry for a directory.
      log(`  Skipping ${testPath} because actual is missing`);
      return null;
    }
    return result;
  }

  rebaseline(expectations) {
    for (let result of this) {
      result.rebaseline(this, expectations);
    }
  }

  static get defaultPath() {
    const outDir = process.env.CHROMIUM_OUTPUT_DIR;
    return path.resolve(outDir, 'layout-test-results', 'full_results.json');
  }
}

async function run(args) {
  let expectations = options.file ? new TestExpectations(options.file) : null;
  log(`Checking test results for: ${Object.keys(options.expects).join(', ')}`);
  for (let key of Object.keys(options.expects))
    statistics[key] = 0;

  log(`Loading results: ${args.join(' ')}`);
  args = TestResults.loadArgs(args);
  let messages = [];
  for (let results of args) {
    results = await results;
    if (!expectations) {
      expectations = new TestExpectations(path.resolve(results.testRootDir, 'TestExpectations'));
    }
    if (options.shouldRebaseline) {
      results.rebaseline(expectations);
    } else if (options.deflake) {
      expectations.addActualExpectations(results);
    } else {
      expectations.update(results);
    }
    messages.push(results.message);
  }

  let summary = ['Update summary:'];
  if (options.remove) {
    let missingTests = expectations.removeIfNotExists();
    summary.push(`  Removed due to missing tests: ${missingTests}`);
  }
  if (options.deflake) {
    expectations.deflake();
  }

  if (async_tasks.length) {
    log('Waiting for all rebaseline tasks to copmlete');
    await Promise.all(async_tasks);
  }

  if (log.warnings.length) {
    log('WARNINGS:');
    for (let warning of log.warnings)
      log(warning);
  }
  let changeCount = 0;
  for (let key in statistics) {
    let value = statistics[key];
    changeCount += value;
    summary.push(`  ${key}: ${value}`);
  }
  log(summary.join('\n'));

  if (options.sort)
    expectations.sort();
  expectations.write();
  log.files.push(expectations.path);

  if (log.files.length) {
    log(`git: Adding ${log.files.length} files`);
    child_process.spawnSync('git', ['add'].concat(log.files), { stdio: 'inherit' });
    if (!options['no-commit']) {
      messages = messages.join(' ');
      log(`git: Committing ${messages}`);
      child_process.spawnSync('git', ['commit', '-m', messages], { stdio: 'inherit' });
    }
  }
}

if (require.main === module) {
  options = parseArgs();
  run(options._).catch(err => {
    console.log(err);
    process.exit(1);
  });
} else {
  module.exports = run;
  module.exports.parseArgs = parseArgs;
  module.exports.setArgs = args =>
      options = parseArgs(args);
  module.exports.TestExpectation = TestExpectation;
  module.exports.TestExpectations = TestExpectations;
  module.exports.TestResult = TestResult;
  module.exports.TestResults = TestResults;
  module.exports.TestResultTypes = TestResultTypes;
}
